import MemberPlaceholder from "../assets/member-placeholder.svg";
import MemberIskandarTursunov from "../assets/members/iskandar-tursunov.png";
import MemberHayotjonAzimov from "../assets/members/hayotjon-azimov.png";
import MemberBaxtiyorjonFayzullayev from "../assets/members/baxtiyorjon-fayzullayev.png";
import MemberOybekXojimamatov from "../assets/members/oybek-xojimamatov.png";
import MemberNuraliSaidov from "../assets/members/nurali-saidov.jpg";
import MemberOnaxonRaximova from "../assets/members/onaxon-raximova.jpg";
import MemberOybekAbdurahimov from "../assets/members/oybek-abdurahimov.jpg";
import MemberNilufarBabanazarova from "../assets/members/nilufar-babanazarova.png";
import MemberOlmosXolboboyev from "../assets/members/olmos-xolboboyev.jpg";
import MemberPaxlavonChinpulatov from "../assets/members/paxlavon-chinpulatov.png";
import MemberAxrorjonSadullayev from "../assets/members/axrorjon-sadullayev.png";
import MemberSurayyoShaamirova from "../assets/members/surayyo-shaamirova.jpg";
import MemberUmrbekRajabov from "../assets/members/umrbek-rajabov.png";
import MemberBaxromXojiyev from "../assets/members/baxrom-xojiyev.jpg";

/**
 * A'zolar ro'yxati — "Info for immh website" Excel faylidan olingan mock ma'lumot.
 *
 * Rasmlar: src/assets/members/ papkasida (1–14). Rasmi hali yo'q a'zolar (15–18)
 * vaqtincha kommentga olingan. Rasm qo'yish uchun uni shu papkaga joylab,
 * import qiling, a'zoni kommentdan chiqaring va `image` maydoniga bering.
 *
 * `code` — davlat kodi (src/lib/data.jsx dagi countryList bilan bir xil).
 * Excel faylida davlat ustuni yo'q edi, shuning uchun barchasi "UZ" qilib qo'yildi.
 */
export const membersData = [
  {
    id: 1,
    name_uz: "Iskandar Tursunov",
    name_en: "Iskandar Tursunov",
    code: "UZ",
    image: MemberIskandarTursunov,
    certificates: "Master in Islamic Finance Practice from INCEIF University, Certified Shari’ah Advisor and Auditor (CSAA)",
    description_uz: "Iskandar Tursunov islomiy moliya bo‘yicha kuchli akademik tayyorgarlikka ega mutaxassis bo‘lib, \"INCEIF University\" (Malayziyada) Master in Islamic Finance Practice (MIFP) darajasini olgan. Shuningdek, u \"Istanbul Sabahattin Zaim University (Turkiya)\"da islomiy moliya bo‘yicha Erasmus almashuv dasturida qatnashgan hamda Toshkent Moliya Institutida “Buxgalteriya hisobi va audit” yo‘nalishida bakalavr darajasini olgan. U AAOIFI Certified Shari'ah Advisor and Auditor (CSAA) sertifikatiga ega bo‘lib, shariat boshqaruvi va muvofiqlik (compliance) yo‘nalishlarida e’tirof etilgan kompetensiyasini namoyon etadi. Uning professional tajribasi O‘zbekistonning iqtisodiy siyosat institutlaridagi yuqori lavozimlari bilan alohida ajralib turadi: u Iqtisodiy taraqqiyot va kambag‘allikni qisqartirish vazirligida bo‘lim boshlig‘i hamda Iqtisodiyot vazirligida bosh mutaxassis sifatida makroiqtisodiy va tarmoq tahlillari, prognozlash, siyosiy dasturlarni ishlab chiqish hamda yetakchi tashkilotlar bilan xalqaro hamkorlik ishlariga rahbarlik qilgan. U keyinchalik Sanoat bozorlari tadqiqotlari markazida bo‘lim boshlig‘i sifatida tahliliy va rahbarlik salohiyatini yanada mustahkamlagan, shuningdek xususiy sektorda \"SAT & Co Holding A.S.\" (Turkiyada) moliyaviy mutaxassis sifatida tajriba orttirgan. 2024-yildan buyon u Al Muamalat Consulting kompaniyasining asoschisi va direktori sifatida islomiy moliya tamoyillariga muvofiqlik bo‘yicha maslahatlar, sukuk strukturasi va kadrlar salohiyatini oshirish yo‘nalishlarida loyihalarga yetakchilik qilib, moliyaviy institutlar, banklar va tegishli manfaatdor tomonlar bilan hamkorlikda ishlamoqda. Umuman olganda, u strategik qarash, kuchli yetakchilik va islomiy moliyaning axloqiy, barqaror hamda yuqori standartlarga asoslangan amaliyotini rivojlantirishga sodiqligi bilan e’tirof etiladi.",
    description_en: "Iskandar Tursunov is an Islamic finance specialist with a strong academic foundation, holding a Master in Islamic Finance Practice (MIFP) from INCEIF University (Malaysia), complemented by an Erasmus Exchange in Islamic Finance at Istanbul Sabahattin Zaim University (Türkiye) and a Bachelor’s degree in Accounting and Audit from Tashkent Financial Institute. He is an AAOIFI Certified Shariah Advisor & Auditor (CSAA), demonstrating recognized competence in Shariah governance and compliance. His professional experience is particularly distinguished by senior roles in Uzbekistan’s economic policy institutions, including Head of Division at the Ministry of Economic Development & Poverty Reduction (2020–2021) and Chief Specialist at the Ministry of Economy (2018–2019), where he led macroeconomic and sectoral analysis, forecasting, policy program development, and international cooperation with key organizations. He further strengthened his analytical and leadership profile as Head of Division at the Centre for Studies of Industrial Markets (2019–2020) and gained private-sector finance exposure as a Financial Specialist at SAT & Co Holding A.S. (Türkiye) (2012–2013). Since 2024, he has served as Founder & CEO of Al Muamalat Consulting, leading advisory engagements in Shariah compliance, Sukuk structuring, and capacity development, while collaborating with financial institutions and relevant stakeholders. Overall, he is recognized for strategic vision, strong leadership, and a consistent commitment to advancing ethical, sustainable, and high-standard Islamic finance practice.",
  },
  {
    id: 2,
    name_uz: "Hayotjon Azimov",
    name_en: "Hayotjon Azimov",
    code: "UZ",
    image: MemberHayotjonAzimov,
    certificates: "Chartered Islamic Finance Professional (CIFP) from INCEIF, Certified Shari’ah Advisor and Auditor (CSAA)",
    description_uz: "Hayotjon Azimov islomiy moliya sohasida katta tajribaga ega bo‘lgan, kuchli akademik va kasbiy tayyorgarlikka ega mutaxassisdir. U \"INCEIF (Malayziya)\"dan Chartered Islamic Finance Professional (CIFP) malakasini olgan hamda Toshkent davlat iqtisodiyot universitetida iqtisodiyot yo‘nalishida ta’lim olgan. U AAOIFI Certified Shari'ah Advisor and Auditor (CSAA) sertifikatiga ega bo‘lib, shariat boshqaruvi, muvofiqlik va \"assurance\" yo‘nalishlarida e’tirof etilgan kompetensiyasini tasdiqlaydi. Uning ish tajribasi bank, kapital bozorlari va takaful sohalarida keng qamrovli, amaliy rahbarlik faoliyati bilan ajralib turadi: Al Muamalat Consultingda Maslahat yo‘nalishi rahbari sifatida u Islomiy banklar to‘g‘risidagi qonun loyihasini ishlab chiqilishiga hissa qo'shib, Islomiy Bank darchalarni joriy etish hamda blokcheyn va tokenizatsiya texnologiyalarining islomiy moliya tamoyillariga muvofiq qo‘llanishi bo‘yicha maslahatlar bergan; shuningdek, Apex OILA Takafulda Islomiy sug‘urta “darcha”si rahbari sifatida (2022–2023) \"Oila Takaful\" yo‘nalishini yo‘lga qo‘ygan. Avvalroq u BNP Paribas Malaysiada (2010–2015) islomiy g'aznachilik, ALM va derivativlar yo‘nalishlarida murakkab shariatga muvofiq yechimlarni ishlab chiqish hamda bir nechta yurisdiktsiyalar bo‘yicha bitim hujjatlarini tayyorlash orqali mahsulot strukturasi bo‘yicha chuqur tajriba to‘plagan, faoliyatini esa CIMB Islamicda (2008–2009) sukuk va investitsion bank xizmatlari yo‘nalishida boshlagan. Umuman olganda, Hayotjon Azimov yuqori texnik salohiyat, manfaatdor tomonlar bilan samarali ishlash ko‘nikmalari hamda yuqori standartlarga mos islomiy moliya bo‘yicha maslahat va strukturaviy xizmatlarni izchil professional tarzda taqdim etishi bilan e’tirof etiladi.",
    description_en: "Hayotjon Azimov is a seasoned Islamic finance professional with a strong academic and professional foundation, holding a Chartered Islamic Finance Professional (CIFP) qualification from INCEIF (Malaysia) and formal economics training at the Tashkent State University of Economics. He is an AAOIFI Certified Shariah Advisor and Auditor (CSAA), evidencing recognized competence in Shariah governance, compliance, and assurance. His work experience is distinguished by extensive, hands-on leadership across banking, capital markets, and takaful: as Head of Advisory at Al Muamalat Consulting he has advised on the drafting of the Islamic Banking Bill, the establishment of Islamic Banking Windows, and Shariah-compliant applications of blockchain and tokenization; and as Head of Islamic Insurance Window at Apex OILA Takaful (2022–2023) he established a Family Takaful window. Earlier, he developed deep product structuring expertise at BNP Paribas Malaysia (2010–2015) in Islamic treasury, ALM and derivatives, delivering complex Shariah-compliant solutions and transaction documentation across multiple jurisdictions, and began his career in sukuk and investment banking at CIMB Islamic (2008–2009). Overall, he is recognized for rigorous technical proficiency, strong stakeholder management, and consistent professionalism in delivering high-standard Islamic finance advisory and structuring services.",
  },
  {
    id: 3,
    name_uz: "Baxtiyorjon Fayzullayev",
    name_en: "Bakhtiyorjon Fayzullaev",
    code: "UZ",
    image: MemberBaxtiyorjonFayzullayev,
    certificates: "Certificate of Proficiency in Shari’ah Standards (CPSS)",
    description_uz: "Baxtiyorjon Fayzullayev moliya va islomiy bank ishi yo‘nalishida faoliyat yurituvchi, mustahkam akademik tayyorgarlikka ega mutaxassis bo‘lib, Jahon iqtisodiyoti va diplomatiya universitetida “Xalqaro iqtisodiyot va menejment” yo‘nalishi bo‘yicha bakalavr darajasini olgan. Shuningdek, u ilg‘or professional malakalarga, jumladan AAOIFI Certificate of Proficiency in Shari’ah Standards (CPSS) sertifikatiga hamda Financial Modeling & Valuation Analyst (FMVA) sertifikatiga ega. Uning ish tajribasi hozirda Al Muamalat Consulting kompaniyasida Katta maslahatchi sifatidagi faoliyatini qamrab olib, u yerda Islomiy Bank Darchalarini tashkil etish bo‘yicha maslahatlar beradi, islomiy moliya mahsulotlarini strukturaviy ishlab chiqish va hujjatlashtirish jarayonlarini qo‘llab-quvvatlaydi hamda islomiy moliya va islomiy bank ishi bo‘yicha o‘quv-trening dasturlarini koordinatsiya qiladi. Avvalroq u KPMG Uzbekistanda konsultant sifatida kasbiy ta’lim va trening dasturlarini ishlab chiqish va modernizatsiya qilish ishlarida ishtirok etgan, banklar va davlat muassasalari uchun risk-menejment, ichki audit, IFRS va moliyaviy tahlil bo‘yicha professional treninglarni koordinatsiya qilgan, shuningdek MDH mintaqasidagi xalqaro mijozlar uchun \"gap analysis\" o‘tkazgan. Uning davlat sektoridagi tajribasi Investitsiyalar, sanoat va savdo vazirligidagi amaliyot orqali bozor tadqiqotlari, makroiqtisodiy tahlil, investitsion imkoniyatlar bo‘yicha hisobotlar tayyorlash va rasmiy yozishmalar bilan ishlashni o‘z ichiga oladi, shuningdek avvalgi amaliyotlari hujjatlar nazorati, hisobot yuritish va arxiv/registratsiya jarayonlari bilan bog‘liq bo‘lgan. Umuman olganda, Baxtiyorjon Fayzullayev kuchli analitik salohiyat, hujjatlashtirishda yuqori intizom va sifatli maslahat hamda salohiyatni oshirish (capacity-building) yo‘nalishlarida barqaror professional yondashuvi bilan ajralib turadi.",
    description_en: "Bakhtiyorjon Fayzullaev is a finance and Islamic banking professional with a solid academic background, holding a Bachelor’s degree in International Economics and Management from the University of World Economy and Diplomacy and advanced professional qualifications including the AAOIFI Certificate of Proficiency in Shari’ah Standards (CPSS) and the Financial Modeling & Valuation Analyst (FMVA) credential. His work experience includes his current role as Senior Associate at Al Muamalat Consulting, where he advises on establishing Islamic Banking Windows, supports the structuring and documentation of Islamic finance products, and coordinates training programs in Islamic finance and Islamic banking. Previously, as a Consultant at KPMG Uzbekistan, he contributed to the design and modernization of vocational education and training programs, coordinated professional trainings on risk management, internal audit, IFRS, and financial analysis for banks and public-sector institutions, and conducted gap analyses for international clients across the CIS region. His public-sector exposure includes an internship at the Ministry of Investments, Industry and Trade focused on market research, macroeconomic analysis, investment opportunity reporting, and official correspondence, as well as earlier internships involving documentation control, reporting, and records management. Overall, he is distinguished by strong analytical capability, disciplined documentation standards, and a consistent commitment to professionalism in delivering high-quality advisory and capacity-building support.",
  },
  {
    id: 4,
    name_uz: "Oybek Xojimamatov",
    name_en: "Oybek Khojimamatov",
    code: "UZ",
    image: MemberOybekXojimamatov,
    certificates: "Certificate of Proficiency in Shari’ah Standards (CPSS) & Certificate of Proficiency in Financial Accounting Standards (CPFAS)",
    description_uz: "Oybek Xojimamatov islomiy moliya va buxgalteriya hisobi yo‘nalishida shakillanib borayotgan mutaxassis bo‘lib, u kuchli akademik tayyorgarlikka ega: University of South Florida universitetida buxgalteriya hisobi bo‘yicha Bakalavr darajasini olgan hamda Université Lavalda xalqaro \"study-abroad\" dasturini muvaffaqiyatli yakunlagan, bundan tashqari avvalroq biznes ta’limi bo‘yicha tayyorgarlikdan ham o‘tgan. U AAOIFIning ikki malaka sertifikatini — Certificate of Proficiency in Shari’ah Standards (CPSS) va Certificate of Proficiency in Financial Accounting Standards (CPFAS) — muvaffaqiyatli qo‘lga kiritib, islomiy moliya standartlari hamda islomiy moliyaviy hisob talablari bo‘yicha tizimli bilimga ega ekanini namoyon etadi. Uning amaliy tajribasi universitetdagi o‘qish jarayonida Talabalar yetakchisi sifatida akademik faoliyatda ishtirok etishi, shuningdek Al-Muamalat Consulting bilan tuzilgan va tartibli o‘qish (structured learning) orqali kasbiy rivojlanish jarayonida faol qatnashishini o‘z ichiga olib, bu uning amaliy kompetensiyalarni shakllantirishda intizomli va standartlarga yo‘naltirilgan yondashuvini aks ettiradi. Umuman olganda, Oybek Xojimamatov tirishqoqligi, uzluksiz o‘rganishga intilishi hamda islomiy moliyani halollik va qat’iy professional mezonlar asosida rivojlantirishga sodiqligi bilan ajralib turadi.",
    description_en: "Oybek Khojimamatov is an emerging Islamic finance and accounting specialist with a strong academic foundation, having earned a B.S. in Accounting from the University of South Florida and completed an international study-abroad program at Université Laval, supported by earlier business education training. He has successfully obtained two AAOIFI proficiency certificates — the Certificate of Proficiency in Shari’ah Standards (CPSS) and the Certificate of Proficiency in Financial Accounting Standards (CPFAS) — demonstrating structured knowledge of Shari'ah standards and Islamic financial accounting requirements. His practical experience includes academic work as a Student Assistant during his university studies and active engagement in professional development through structured learning with Al-Muamalat Consulting, reflecting a disciplined, standards-oriented approach to building applied expertise. Overall, he is distinguished by diligence, continuous learning, and a professional commitment to contributing to the advancement of Islamic finance with integrity and rigor.",
  },
  {
    id: 5,
    name_uz: "Nurali Saidov",
    name_en: "Nurali Saidov",
    code: "UZ",
    image: MemberNuraliSaidov,
    certificates: "Certificate of Proficiency in Shari’ah Standards (CPSS) & Certificate of Proficiency in Financial Accounting Standards (CPFAS)",
    description_uz: "Nurali Saidov — menejment yo‘nalishi bo‘yicha Toshkent Davlat Iqtisodiyot Universiteti bitiruvchisi bo‘lib, bank-moliya va real sektor kesishmasida shakllangan keng ko‘lamli amaliy tajribaga ega mutaxassisdir. U faoliyati davomida davlat tashkilotida iqtisodchi sifatida ishlashdan boshlab, xususiy korxonalarda buxgalteriya va moliyaviy boshqaruv yo‘nalishlarida mas’ul lavozimlarda, jumladan bosh hisobchi, bosh hisobchi o‘rinbosari, direktor hamda rahbarlik pozitsiyalarida samarali faoliyat yuritgan. Savdo-sanoat tizimidagi tajribasi unga korporativ boshqaruv, moliyaviy hisobot va nazorat, shuningdek, tashkilotlar faoliyatini muvofiqlashtirish bo‘yicha mustahkam ko‘nikmalarni shakllantirgan. Shuningdek, u AAOIFIning Certificate of Proficiency in Shari’ah Standards (CPSS) hamda Certificate of Proficiency in Financial Accounting Standards (CPFAS) sertifikatlariga ega bo‘lib, Islomiy moliya standartlari va islomiy moliyaviy hisob standartlari bo‘yicha professional bilim hamda amaliy yondashuvini tasdiqlaydi. Umuman olganda, Nurali Saidov yuqori mas’uliyat, tizimli fikrlash va amaliy natijaga yo‘naltirilgan professional yondashuvi bilan ajralib turadigan malakali mutaxassisdir.",
    description_en: "Nurali Saidov is a graduate of the Tashkent State University of Economics with a degree in Management, and a specialist with extensive practical experience developed at the intersection of the banking/finance sector and the real economy. Over the course of his career, he has progressed from working as an economist in a public institution to holding responsible positions in private companies in accounting and financial management, including Chief Accountant, Deputy Chief Accountant, Director, and other leadership roles, where he has delivered strong professional performance. His experience within the trade and industry system has enabled him to build solid competencies in corporate governance, financial reporting and control, as well as the coordination of organizational operations. He also holds two AAOIFI certificates — Certificate of Proficiency in Shari’ah Standards (CPSS) and Certificate of Proficiency in Financial Accounting Standards (CPFAS) — which confirm his professional knowledge and practical approach to Shari’ah standards and Islamic financial accounting standards. Overall, Nurali Saidov is a qualified specialist distinguished by a high sense of responsibility, structured thinking, and a results-oriented professional approach.",
  },
  {
    id: 6,
    name_uz: "Onaxon Raximova",
    name_en: "Onakhon Rakhimova",
    code: "UZ",
    image: MemberOnaxonRaximova,
    certificates: "Certificate of Proficiency in Financial Accounting Standards (CPFAS)",
    description_uz: "Onaxon Raximova — buxgalteriya hisobi, audit va moliyaviy nazorat sohalarida mustahkam akademik tayyorgarlikka ega mutaxassis bo‘lib, Toshkent davlat transport universitetida “Buxgalteriya hisobi va audit” yo‘nalishida bakalavr darajasini hamda Toshkent Moliya institutida “Audit” yo‘nalishida magistr darajasini olgan. Shuningdek, u hozirda Toshkent iqtisodiyot universitetida PhD bosqichida ilmiy izlanish olib bormoqda. Mehnat faoliyati davomida u oliy ta’lim muassasasida iqtisodchi sifatida iqtisodiy tahlil, rejalashtirish va hisob-kitob jarayonlarida ishtirok etgan, keyinchalik Toshkent shahar hokimiyatida investitsiya yo‘nalishidagi bo‘limda bosh hisobchi sifatida moliyaviy hisobot, budjet intizomi va nazorat jarayonlarini yuritgan. Hozirda u “Xadichai Kubro” ayol-qizlar o‘rta maxsus islom ta’lim muassasasida bosh hisobchi sifatida moliyaviy boshqaruv, hisob siyosati va hisobotlarning to‘g‘ri yuritilishini ta’minlab kelmoqda. Shuningdek, u AAOIFIning Certificate of Proficiency in Financial Accounting Standards (CPFAS) sertifikatiga ega bo‘lib, islomiy moliyaviy hisobot standartlari bo‘yicha professional bilim va malakasini tasdiqlaydi. Umuman olganda, Onaxon Raximova mas’uliyatli yondashuvi, tartib-intizomi, tizimli fikrlashi hamda yuqori professionalligi bilan ajralib turadigan ishonchli mutaxassisdir.",
    description_en: "Onakhon Rakhimova is a specialist with a strong academic background in accounting, auditing, and financial control. She earned a Bachelor’s degree in Accounting and Audit from the Tashkent State Transport University and a Master’s degree in Audit from the Tashkent Institute of Finance. She is also currently pursuing PhD-level research at the Tashkent State University of Economics. Throughout her career, she has contributed as an economist in a higher education institution, participating in economic analysis, planning, and settlement processes. She later served as a Chief Accountant in an investment-focused department of the Tashkent City Administration, overseeing financial reporting, budget discipline, and control procedures. She currently works as Chief Accountant at the “Xadichai Kubro” women’s secondary specialized Islamic educational institution, ensuring effective financial management, sound accounting policies, and accurate reporting. She also holds the AAOIFI Certificate of Proficiency in Financial Accounting Standards (CPFAS), confirming her professional knowledge and competence in Islamic financial reporting standards. Overall, Onakhon Rakhimova is a reliable professional distinguished by a responsible approach, strong discipline, structured thinking, and high standards of professionalism.",
  },
  {
    id: 7,
    name_uz: "Oybek Abdurahimov",
    name_en: "Oybek Abdurakhimov",
    code: "UZ",
    image: MemberOybekAbdurahimov,
    certificates: "Certificate of Proficiency in Shari’ah Standards (CPSS) & Certificate of Proficiency in Financial Accounting Standards (CPFAS)",
    description_uz: "Oybek Abdurahimov — bank ishi va xalqaro valyuta-kredit munosabatlari yo‘nalishlarida mustahkam akademik tayyorgarlikka ega, moliya sohasida ko‘p yillik amaliy tajriba to‘plagan mutaxassisdir. U Toshkent Moliya institutida “Bank ishi” yo‘nalishi bo‘yicha bakalavr hamda “Xalqaro valyuta-kredit munosabatlari” yo‘nalishi bo‘yicha magistr darajasini olgan. Professional faoliyati bank tizimida boshlangan bo‘lib, u “Asakabank”ning hududiy bo‘linmasida buxgalteriya yo‘nalishida ishlashdan keyin bosh hisobchi o‘rinbosari sifatida moliyaviy hisobot, buxgalteriya nazorati va bank operatsiyalarini hisobga olish jarayonlarida yetakchi vazifalarni bajargan. Keyinchalik “Aloqabank”da hududiy filial bosh buxgalteri sifatida buxgalteriya hisobi va ichki nazorat tizimlarini yuritgan, so‘ng bank markazi rahbari sifatida operatsion boshqaruv va moliyaviy intizomni ta’minlash bo‘yicha mas’uliyatli rahbarlik tajribasini shakllantirgan. Hozirda u xususiy korxonada auditor sifatida faoliyat yuritib, moliyaviy tekshiruvlar, hisobotlar ishonchliligi va risklarni baholash yo‘nalishlarida professional xizmatlar ko‘rsatmoqda. Shuningdek, u AAOIFIning Certificate of Proficiency in Shari’ah Standards (CPSS) hamda Certificate of Proficiency in Financial Accounting Standards (CPFAS) sertifikatlariga ega bo‘lib, shariat standartlari va islomiy moliyaviy hisob standartlari bo‘yicha kasbiy bilimini tasdiqlaydi. Umuman olganda, Oybek Abdurahimov mas’uliyat, aniqlik, tizimli yondashuv va natijadorlikka yo‘naltirilgan professional ish uslubi bilan ajralib turadigan ishonchli mutaxassisdir.",
    description_en: "Oybek Abdurakhimov is a finance professional with a strong academic background in banking and international monetary and credit relations, supported by many years of practical experience in the financial sector. He earned a Bachelor’s degree in Banking and a Master’s degree in International Monetary and Credit Relations from the Tashkent Institute of Finance. He began his career in the banking system at a regional branch of Asakabank, initially working in accounting and subsequently serving as Deputy Chief Accountant, where he held leading responsibilities in financial reporting, accounting control, and the recording of banking operations. He later worked at Aloqabank as Chief Accountant of a regional branch, overseeing accounting and internal control systems, and subsequently as Head of a bank center, developing strong leadership experience in operational management and ensuring financial discipline. He currently works as an auditor in a private company, providing professional services in financial inspections, assurance of reporting reliability, and risk assessment. He also holds two AAOIFI certificates — Certificate of Proficiency in Shari’ah Standards (CPSS) and Certificate of Proficiency in Financial Accounting Standards (CPFAS) — confirming his professional knowledge of Shari’ah standards and Islamic financial accounting standards. Overall, Oybek Abdurakhimov is a reliable specialist distinguished by responsibility, accuracy, a structured approach, and a results-oriented professional work style.",
  },
  {
    id: 8,
    name_uz: "Nilufar Babanazarova",
    name_en: "Nilufar Babanazarova",
    code: "UZ",
    image: MemberNilufarBabanazarova,
    certificates: "Certificate of Proficiency in Shari’ah Standards (CPSS)",
    description_uz: "Nilufar Babnazarova — bank ishi hamda bank va kredit risklarini boshqarish yo‘nalishlarida mustahkam akademik tayyorgarlikka ega, bank, audit va ta’lim sohalarida izchil amaliy tajriba to‘plagan mutaxassisdir. U Toshkent Moliya institutida “Bank ishi” yo‘nalishi bo‘yicha bakalavr hamda “Bank va kredit risklari” yo‘nalishi bo‘yicha magistr darajasini olgan. Faoliyati davomida u “Hamkorbank”da ma’muriy-boshqaruv xarajatlarini boshqarish yo‘nalishida mutaxassis sifatida moliyaviy rejalashtirish va xarajatlar nazorati bilan shug‘ullangan, keyinchalik “Smart Audit” kompaniyasida buxgalter-konsultant va auditor yordamchisi sifatida moliyaviy hisobotlarni tahlil qilish, audit jarayonlarini qo‘llab-quvvatlash hamda buxgalteriya masalalari bo‘yicha maslahatlar berish bo‘yicha muhim ko‘nikmalarni shakllantirgan. Shuningdek, u O‘zbekiston Respublikasi Bank-moliya Akademiyasida o‘qituvchi sifatida bank-moliya yo‘nalishida bilim va tajribasini uzatgan, hozirda esa ushbu akademiyada doktorant sifatida ilmiy izlanishlar olib bormoqda. Nilufar Babnazarova AAOIFIning Certificate of Proficiency in Shari’ah Standards (CPSS) sertifikatiga ega bo‘lib, islomiy moliya standartlari bo‘yicha professional bilimini tasdiqlaydi. Umuman olganda, u tizimli fikrlash, mas’uliyatli yondashuv, analitik salohiyat va doimiy rivojlanishga intilish kabi professional fazilatlari bilan ajralib turadigan ishonchli mutaxassisdir.",
    description_en: "Nilufar Babanazarova is a specialist with a strong academic background in banking as well as bank and credit risk management, and she has built consistent practical experience across the banking, audit, and education sectors. She earned a Bachelor’s degree in Banking and a Master’s degree in Bank and Credit Risks from the Tashkent Institute of Finance. During her career, she worked at Hamkorbank as a specialist in managing administrative and operational expenses, focusing on financial planning and cost control. She later developed key competencies at Smart Audit as an accounting consultant and audit assistant, where she gained extensive experience in analyzing financial statements, supporting audit processes, and providing guidance on accounting matters. She also served as a lecturer at the Banking and Finance Academy of the Republic of Uzbekistan, sharing her expertise in banking and finance, and she is currently conducting academic research there as a doctoral student. Nilufar Babanazarova holds the AAOIFI Certificate of Proficiency in Shari’ah Standards (CPSS), confirming her professional knowledge of Islamic finance standards. Overall, she is a reliable professional distinguished by structured thinking, a responsible approach, strong analytical capability, and a continuous commitment to professional development.",
  },
  {
    id: 9,
    name_uz: "Olmos Xolboboyev",
    name_en: "Olmos Kholboboyev",
    code: "UZ",
    image: MemberOlmosXolboboyev,
    certificates: "Master’s degree in Islamic Economics and Finance from Istanbul Sabahattin Zaim University (Türkiye), Certified Shari’ah Advisor and Auditor (CSAA), Certificate of Proficiency in Financial Accounting Standards (CPFAS)",
    description_uz: "Olmos Xolboboyev — iqtisodiyot hamda islomiy iqtisodiyot va moliya yo‘nalishlarida kuchli akademik tayyorgarlik va bank tizimida amaliy boshqaruv tajribasiga ega mutaxassis. U Toshkent davlat iqtisodiyot universitetida bakalavr, AQShdagi University of Colorado Denver’da iqtisodiyot bo‘yicha magistr hamda Turkiyadagi Istanbul Sabahattin Zaim University’da islom iqtisodiyoti va moliyasi bo‘yicha magistr darajalarini olgan. Faoliyati davomida Markaziy bank tizimida bank inspeksiyalari va prudensial talablar yo‘nalishlarida ishlagan, keyinchalik KDB Bank Uzbekistan’da kredit tahlili va risk yo‘nalishlarida rahbarlik lavozimlarida faoliyat yuritgan. Hozir islomiy moliya bo‘yicha konsultant sifatida shariatga muvofiqlik, boshqaruv va standartlar asosida mahsulot va jarayonlarni takomillashtirishga ko‘maklashadi. AAOIFI CSAA va CPFAS sertifikatlariga ega.",
    description_en: "Olmos Kholboboyev is a banking and Islamic finance professional with strong academic credentials and practical leadership experience across supervision, credit, and risk functions. He holds a Bachelor’s degree from Tashkent State University of Economics, a Master’s in Economics from the University of Colorado Denver (USA), and a Master’s in Islamic Economics and Finance from Istanbul Sabahattin Zaim University (Türkiye). He began his career within the Central Bank system, working on commercial bank inspections and prudential requirements, and later held managerial roles at KDB Bank Uzbekistan covering credit analysis and risk-related functions. He currently works as an Islamic finance consultant, supporting Shariah-compliant governance and the implementation of international standards. He holds AAOIFI CSAA and CPFAS certifications.",
  },
  {
    id: 10,
    name_uz: "Paxlavon Chinpulatov",
    name_en: "Pakhlavon Chinpulatov",
    code: "UZ",
    image: MemberPaxlavonChinpulatov,
    certificates: "Certified Shari’ah Advisor and Auditor (CSAA)",
    description_uz: "Paxlavon Chinpulatov — xalqaro iqtisodiyot va moliya yo‘nalishlarida mustahkam akademik tayyorgarlikka ega, kapital bozori infratuzilmasida amaliy tajribaga ega bo‘lgan mutaxassisdir. U Jahon iqtisodiyoti va diplomatiya universitetida “Xalqaro iqtisodiyot va menejment” yo‘nalishi bo‘yicha bakalavr darajasini olgan hamda O‘zbekiston Respublikasi Bank-moliya akademiyasida “Korporativ moliya va qimmatli qog‘ozlar bozori” yo‘nalishida magistratura bosqichida tahsil olmoqda. Professional faoliyati davomida u “Qimmatli qog‘ozlar markaziy depozitariysi” AJda turli lavozimlarda ishlash orqali qimmatli qog‘ozlar bozorining post-treyd infratuzilmasi, hisob-kitob va saqlash jarayonlari, shuningdek, institutsional mijozlar bilan ishlash bo‘yicha muhim amaliy ko‘nikmalarni shakllantirgan. Hozirda u ushbu tashkilotda chet ellik nominal saqlovchilarga xizmat ko‘rsatish va SWIFT xabarlari bilan ishlash bo‘limi boshlig‘i sifatida xalqaro amaliyotga mos operatsion jarayonlarni boshqarish, xizmatlar sifati va tartib-taomillarning aniq bajarilishini ta’minlash yo‘nalishlarida mas’uliyatli rahbarlik faoliyatini olib bormoqda. Shuningdek, u AAOIFIning Certified Shari’ah Advisor and Auditor (CSAA) sertifikatiga ega bo‘lib, islomiy moliya tamoyillarga muvofiqlik, shariat boshqaruvi va audit bo‘yicha professional kompetensiyasini tasdiqlaydi. Umuman olganda, Paxlavon Chinpulatov tizimli fikrlash, yuqori mas’uliyat, xalqaro standartlar bilan ishlash madaniyati hamda natijadorlikka yo‘naltirilgan professional yondashuvi bilan ajralib turadigan, islomiy moliya hamjamiyati uchun istiqbolli va ishonchli mutaxassisdir.",
    description_en: "Pakhlavon Chinpulatov is a specialist with a solid academic background in international economics and finance, and practical experience in capital market infrastructure. He earned a Bachelor’s degree in International Economics and Management from the University of World Economy and Diplomacy and is currently pursuing a Master’s program in Corporate Finance and Securities Markets at the Banking and Finance Academy of the Republic of Uzbekistan. Throughout his professional career, he has held various positions at the Central Securities Depository, where he developed strong hands-on expertise in post-trade market infrastructure, settlement and custody processes, as well as working with institutional clients. He currently serves as Head of the Department for Services to Foreign Nominee Holders and SWIFT Messaging, leading operational processes aligned with international practice and ensuring service quality and strict adherence to established procedures. He also holds the AAOIFI Certified Shari’ah Advisor and Auditor (CSAA) certificate, confirming his professional competence in Shari’ah compliance, Shari’ah governance, and audit in line with Islamic finance principles. Overall, Pakhlavon Chinpulatov is a promising and reliable professional distinguished by structured thinking, a high sense of responsibility, a strong culture of working with international standards, and a results-oriented approach.",
  },
  {
    id: 11,
    name_uz: "Axrorjon Sadullayev",
    name_en: "Akhrorjon Sadullaev",
    code: "UZ",
    image: MemberAxrorjonSadullayev,
    certificates: "MBA in Islamic Finance at the Banking and Finance Academy of Uzbekistan, Certified Shari’ah Advisor and Auditor (CSAA)",
    description_uz: "Axrorjon Sadullayev — buxgalteriya hisobi, audit va islomiy moliya yo‘nalishlarida puxta tayyorgarlik va katta amaliy tajribaga ega mutaxassis. U Toshkent Moliya institutida “Buxgalteriya hisobi va audit” bo‘yicha bakalavr, O‘zbekiston Bank-moliya akademiyasida MBA in Islamic Finance darajasini olgan. Faoliyati davomida bank tizimida ichki audit va nazorat yo‘nalishlarida ishlagan, Markaziy bankda bosh iqtisodchi sifatida makro va moliyaviy tahlil hamda tartibga solish jarayonlarida ishtirok etgan. Keyinchalik tijorat banklarida ichki auditor bo‘lib risklarni boshqarish, nazorat muhitini kuchaytirish va operatsion samaradorlikni oshirishga qaratilgan auditlar o‘tkazgan. So‘ng **KPMG (Big Four)**da katta auditor sifatida murakkab audit loyihalarini boshqargan, moliyaviy hisobotlar ishonchliligini baholagan hamda korporativ boshqaruv va komplaens amaliyotlarini takomillashtirish bo‘yicha ishlagan. Hozirda auditorlik tashkilotida boshqaruvchi sherik sifatida yuqori standartlarga mos audit va maslahat xizmatlarini taqdim etadi. AAOIFI CSAA sertifikatiga ega.",
    description_en: "Akhrorjon Sadullaev is an experienced professional in accounting, audit, and Islamic finance with a strong academic background and extensive practice in both banking and international audit. He holds a Bachelor’s degree in Accounting and Audit from the Tashkent Institute of Finance and an MBA in Islamic Finance from the Banking and Finance Academy of Uzbekistan. He developed expertise in internal control and audit within the banking system and served as a Chief Economist at the Central Bank, contributing to macroeconomic and financial analysis and regulatory work. He later worked as an internal auditor at commercial banks, conducting audits aimed at strengthening risk management, improving the control environment, and enhancing operational efficiency. He then joined KPMG (Big Four) as a senior auditor, managing complex engagements, assessing financial reporting reliability, and supporting improvements in corporate governance and compliance. He currently serves as a Managing Partner at an audit firm, delivering audit and advisory services aligned with high professional standards. He holds the AAOIFI CSAA certification.",
  },
  {
    id: 12,
    name_uz: "Surayyo Shaamirova",
    name_en: "Sarayyo Shaamirova",
    code: "UZ",
    image: MemberSurayyoShaamirova,
    certificates: "PhD from Institute of Islamic Economics and Finance, Istanbul University, Master’s degree in Islamic Banking and Finance at International Islamic University Malaysia (IIUM), Certified Shari’ah Advisor and Auditor (CSAA)",
    description_uz: "Surayyo Shaamirova — moliya va islomiy bank ishi yo‘nalishlarida xalqaro akademik tayyorgarlik hamda ko‘p tarmoqli amaliy tajribaga ega mutaxassis. U International Islamic University Malaysia (IIUM)da moliya bo‘yicha bakalavr hamda islomiy bankchilik va moliya bo‘yicha magistr darajalarini olgan. Shuningdek, Istanbul University qoshidagi Institute of Islamic Economics and Financeda PhD bosqichida ilmiy izlanishlar olib borgan. Professional faoliyati davomida auditor sifatida moliyaviy hisobotlar, nazorat va muvofiqlik jarayonlari bo‘yicha amaliy ko‘nikmalarni shakllantirgan; keyinchalik shartnomalar boshqaruvi va marketing yo‘nalishlarida mas’ul lavozimlarda ishlab, biznes jarayonlarini boshqarish va bozor tahlili bo‘yicha tajribasini kengaytirgan. Toshkent shahridagi Westminster International University (WIUT)da strategik rivojlanish va ma’lumotlarni boshqarish bo‘yicha rahbarlik vazifalarini bajargan, bozor tadqiqotlari va analitika yo‘nalishida yetakchi mutaxassis sifatida faoliyat yuritgan hamda universitetda o‘qituvchilik qilgan. Hozirda Bank-moliya akademiyasida katta o‘qituvchi sifatida islomiy moliya va bank ishi bo‘yicha amaliyotga yo‘naltirilgan ta’lim beradi. AAOIFI’ning Certified Shari’ah Advisor and Auditor (CSAA) sertifikatiga ega.",
    description_en: "Surayyo Shaamirova is a finance and Islamic banking professional with a strong international academic background and diverse practical experience. She earned a Bachelor’s degree in Finance and a Master’s degree in Islamic Banking and Finance from the International Islamic University Malaysia (IIUM). She also pursued PhD-level research at the Institute of Islamic Economics and Finance at Istanbul University. Professionally, she gained hands-on experience in financial reporting, internal control, and compliance processes while working as an auditor, and later expanded her expertise through roles in contract management and marketing, strengthening her capabilities in business process management and market analysis. In Tashkent, she held leadership responsibilities in strategic development and data management at Westminster International University (WIUT), worked in market research and analytics, and contributed to teaching activities. She currently serves as a Senior Lecturer at the Banking and Finance Academy, delivering practice-oriented education in Islamic finance and banking. She holds the AAOIFI Certified Shari’ah Advisor and Auditor (CSAA) certification.",
  },
  {
    id: 13,
    name_uz: "Umrbek Rajabov",
    name_en: "Umrbek Rajabov",
    code: "UZ",
    image: MemberUmrbekRajabov,
    certificates: "Master’s degree in Islamic Finance at INCEIF University, Certificate of Proficiency in Shari’ah Standards (CPSS)",
    description_uz: "Umrbek Rajabov — iqtisodiyot va islom moliyasi yo‘nalishlarida mustahkam akademik tayyorgarlikka ega, professional rivojlanishga izchil yondashadigan mutaxassisdir. U Urganch davlat universitetida “Iqtisodiyot (tarmoqlar va sohalar)” yo‘nalishi bo‘yicha bakalavr darajasini olgan hamda INCEIF Universityda “Islom moliyasi” yo‘nalishida magistratura bosqichini tamomlagan. Shuningdek, u AAOIFIning Certificate of Proficiency in Shari’ah Standards (CPSS) sertifikatiga ega bo‘lib, islomiy moliya standartlari bo‘yicha professional bilim va malakasini tasdiqlaydi. Umuman olganda, Umrbek Rajabov puxta akademik baza, tizimli fikrlash va yuqori mas’uliyatga tayangan holda islomiy moliya amaliyotini rivojlantirishga hissa qo‘shishga yo‘naltirilgan, ishonchli va professional mutaxassis sifatida e’tirof etiladi.",
    description_en: "Umrbek Rajabov is a specialist with a solid academic foundation in economics and Islamic finance, characterized by a consistent commitment to professional development. He earned a Bachelor’s degree in Economics (by sectors and industries) from Urgench State University and completed a Master’s degree in Islamic Finance at INCEIF University. He also holds the AAOIFI Certificate of Proficiency in Shari’ah Standards (CPSS), confirming his professional knowledge and competence in Islamic finance standards. Overall, Umrbek Rajabov is recognized as a reliable and professional specialist, distinguished by strong academic preparation, structured thinking, and a high sense of responsibility, with a clear focus on contributing to the advancement of Islamic finance practice.",
  },
  {
    id: 14,
    name_uz: "Baxrom Xojiyev",
    name_en: "Bakhrom Khojiev",
    code: "UZ",
    image: MemberBaxromXojiyev,
    certificates: "Certified Shari’ah Advisor and Auditor (CSAA)",
    description_uz: "Baxrom Xojiev — bank va moliya sohasida 20 yildan ortiq tajribaga ega bo‘lgan, chakana bank biznesi, komplayens va raqamli transformatsiya yo‘nalishlarida yetuk mutaxassisdir. U Bank-Moliya Akademiyasida “Bank auditi” mutaxassisligi bo‘yicha magistr, Toshkent Moliya Institutida “Buxgalteriya hisobi va audit” yo‘nalishi bo‘yicha bakalavr darajasini olgan, hamda AAOIFI Certified Shari’ah Advisor and Auditor (CSAA) sertifikatiga ega. U “Asia Alliance Bank” ATBda ichki nazorat, chakana kreditlash, chakana biznes va elektron tijoratni rivojlantirish bo‘linmalariga rahbarlik qilib, mobil banking platformalari, CRM tizimlari, kredit skoring modellari va raqamli moliyaviy xizmatlarni joriy etgan; keyinchalik “Xalq banki” ATBda komplayens va ichki nazorat departamenti direktori o‘rinbosari sifatida AML/CFT jarayonlarini avtomatlashtirish va nazorat tizimlarini transformatsiya qilishga boshchilik qilgan. 2023–2024-yillarda “Anor Bank” AJda chakana biznes departamenti direktori o‘rinbosari sifatida ishtirok etgan, 2024-yildan buyon “Open Bank” AJda loyiha menejeri sifatida mahsulotlarni loyihalash va joriy etishga rahbarlik qilib kelmoqda; u strategik fikrlashi, kuchli boshqaruv salohiyati hamda axloqiy va barqaror moliya tamoyillariga sodiqligi bilan ajralib turadi.",
    description_en: "Bakhrom Khojiev is a senior banking and finance professional with over 20 years of experience in banking, compliance, and digital transformation. He holds a Master’s degree in Banking from the Banking and Finance Academy of the Republic of Uzbekistan and a Bachelor’s degree in Accounting and Audit from Tashkent Financial Institute, and also an AAOIFI Certified Shari’ah Advisor and Auditor (CSAA). Throughout his career, he has held leadership roles at major Uzbek banks, including Asia Alliance Bank, where he led internal control, retail lending, and e-commerce development, delivering mobile banking platforms, CRM systems, credit scoring models, and digital financial services; Xalq Bank, where he served as Deputy Director of Compliance and Internal Control, leading AML/CFT automation and compliance system transformation; and Anor Bank, where he was Deputy Director of Retail Business. Since 2024, he has been working at Open Bank as a Project Manager for Shari’ah-Compliant Financial Solutions, leading the design and implementation of financial products, and is recognized for his strategic mindset, strong leadership, and commitment to ethical and sustainable finance.",
  },
  // Rasmi hali yo'q — rasm topilgach kommentdan chiqarib, `image` ni yangilang.
  // {
  //   id: 15,
  //   name_uz: "Odiljon Axmadjonov",
  //   name_en: "Odiljon Akhmadjonov",
  //   code: "UZ",
  //   image: MemberPlaceholder,
  //   certificates: "Certified Proficiency in Financial Accounting Standards (CPFAS)",
  //   description_uz: "Odiljon Axmadjonov — bank-moliya va fintech yo‘nalishlarida shakllanayotgan yosh mutaxassis. 2004-yil 25-iyunda O‘zbekiston Respublikasi, Andijon viloyati, Shahrixon tumanida tug‘ilgan. Toshkent davlat iqtisodiyoti universitetida “Moliya va moliyaviy texnologiyalar” yo‘nalishi bo‘yicha bakalavr darajasini tamomlagan. 2023-yil iyun–avgust oylarida AT “Aloqabank”da Korporativ akademiya menejeri, 2023-yil sentyabr–2025-yil sentyabr davrida esa Innovatsion bank xizmatlarini joriy qilish bo‘limida menejer sifatida faoliyat yuritgan. 2025-yil oktyabrdan hozirgacha Malayziya Xalqaro Islom Universitetida (IIUM) “Islom bankchiligi va moliyasi” yo‘nalishida magistratura bosqichida tahsil olmoqda. AAOIFI’ning CPFAS sertifikatiga ega.",
  //   description_en: "Odiljon Akhmadjonov is an emerging banking, finance, and fintech professional. Born on 25 June 2004 in Shahrixon district, Andijan region, Uzbekistan, he holds a Bachelor’s degree from Tashkent State University of Economics, specializing in Finance and Financial Technologies. He gained practical banking experience at Aloqabank, serving as a Corporate Academy Manager (Jun–Aug 2023) and later as a Manager in the Innovative Banking Services Implementation Department (Sep 2023–Sep 2025). Since October 2025, he has been pursuing a Master’s degree at the International Islamic University Malaysia (IIUM) in Islamic Banking and Finance. He is an AAOIFI CPFAS certificate holder.",
  // },
  // {
  //   id: 16,
  //   name_uz: "Shaxzodbek Usmonov",
  //   name_en: "Shakhzodbek Usmonov",
  //   code: "UZ",
  //   image: MemberPlaceholder,
  //   certificates: "Certified Proficiency in Financial Accounting Standards (CPFAS)",
  //   description_uz: "Shaxzodbek Usmonov — bank-moliya sohasida tajribaga ega mutaxassis. 1994-yil 28-iyul kuni O‘zbekiston Respublikasi, Samarqand viloyati, Kattaqo‘rg‘on shahrida tug‘ilgan. Toshkent shahridagi Singapur Menejmentni Rivojlantirish Institutida “Bank ishi va moliya” fakulteti bo‘yicha bakalavr darajasini tamomlagan. 2017-yildan hozirgi kungacha “ATB Kapitalbank”da Savdolarni moliyalashtirish boshqarmasi boshlig‘i lavozimida faoliyat yuritib kelmoqda. AAOIFI’ning CPFAS sertifikatiga ega.",
  //   description_en: "Shakhzodbek Usmonov is a banking and finance professional with strong practical experience. He was born on 28 July 1994 in Kattakurgan city, Samarkand region, Uzbekistan. He holds a Bachelor’s degree in Banking and Finance from the Management Development Institute of Singapore (MDIS) in Tashkent. Since 2017, he has been working at ATB Kapitalbank as the Head of the Trade Finance Department. He holds the AAOIFI CPFAS certificate.",
  // },
  // {
  //   id: 17,
  //   name_uz: "Damira Amanova",
  //   name_en: "Damira Amanova",
  //   code: "UZ",
  //   image: MemberPlaceholder,
  //   certificates: "Certified Proficiency in Financial Accounting Standards (CPFAS)",
  //   description_uz: "Damira Amanova — bank sohasida ko‘p yillik tajribaga ega mutaxassis bo‘lib, savdo moliyalashtirish, loyiha moliyalashtirish hamda moliyaviy institutlar bilan hamkorlik yo‘nalishlarida faoliyat yuritadi. 2004-yilda Toshkent davlat iqtisodiyoti universitetida “Ishlab chiqarish menejmenti” yo‘nalishi bo‘yicha bakalavr, 2010-yilda Bank-moliya akademiyasida “Loyiha moliyalashtirish” yo‘nalishi bo‘yicha magistr darajasini olgan. 2021-yildan buyon ATB “Kapitalbank”da Moliyaviy institutlar bilan hamkorlik departamenti direktori lavozimida ishlaydi. Avval “KDB Bank Uzbekistan” hamda “Paxtabank/Agrobank” tizimlarida savdo moliyalashtirish, kredit va tashqi iqtisodiy faoliyat yo‘nalishlarida rahbarlik lavozimlarida ishlagan. AAOIFI’ning CPFAS sertifikatiga ega.",
  //   description_en: "Damira Amanova is a seasoned banking professional with extensive experience in trade finance, project finance, and cooperation with financial institutions. She earned her Bachelor’s degree from Tashkent State University of Economics (2004, Production Management) and her Master’s degree from the Banking and Finance Academy of Uzbekistan (2010, Project Finance). Since 2021, she has been serving at Kapitalbank as Director within the Department for Cooperation with Financial Institutions. Previously, she held managerial roles at KDB Bank Uzbekistan and built strong expertise in foreign economic activity and banking operations at Pakhtabank/Agrobank. She holds the AAOIFI CPFAS certificate.",
  // },
  // {
  //   id: 18,
  //   name_uz: "Jaxonbek Sayfidinov",
  //   name_en: "Jakhonbek Sayfidinov",
  //   code: "UZ",
  //   image: MemberPlaceholder,
  //   certificates: "Certified Proficiency in Financial Accounting Standards (CPFAS)",
  //   description_uz: "Jaxonbek Sayfidinov — bank amaliyoti va mijozlarga xizmat ko‘rsatish yo‘nalishida tajribaga ega mutaxassis. 1998-yil 17-dekabr kuni O‘zbekiston Respublikasi, Samarqand viloyati, Payariq tumanida tug‘ilgan. Toshkent irrigatsiya va qishloq xo‘jaligini mexanizatsiyalash muhandislari institutida bakalavr, Toshkent davlat iqtisodiyot universitetida magistr darajasini olgan. 2021-yildan buyon “Poytaxt bank” AJda faoliyat yuritib, dastlab Amaliyot boshqarmasining Bek-ofis (buxgalteriya hisobi va hisoboti) bo‘limida buxgalter-nazoratchi sifatida, keyinchalik Front-ofisda yuridik shaxslarga xizmat ko‘rsatish bo‘limida 1-toifali mutaxassis, yetakchi mutaxassis, 2024-yil fevraldan esa bosh mutaxassis lavozimlarida ishlamoqda. AAOIFI’ning CPFAS sertifikatiga ega.",
  //   description_en: "Jakhonbek Sayfidinov is a banking professional with experience in operations and corporate customer service. Born on 17 December 1998 in Payariq district, Samarkand region, Uzbekistan, he holds a Bachelor’s degree from the Tashkent Institute of Irrigation and Agricultural Mechanization Engineers and a Master’s degree from Tashkent State University of Economics. Since 2021, he has worked at Poytaxt Bank JSC, starting in the Operations Department (back office—accounting and reporting) and progressing to front-office roles serving legal entities, including positions as Specialist, Leading Specialist, and since February 2024 as Senior Specialist. He holds the AAOIFI CPFAS certificate.",
  // },
];
